// src/features/teams/api/mocks.ts
import type { ITeam } from '../types'

export const teams: ITeam[] = [
    {
        id: 1,
        name: 'Frontend Team',
        members: [
            {
                id: 1,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                is_owner: true,
                first_name: 'Алексей',
                role: 'Team Lead',
                username: '@test',
            },
            {
                id: 2,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Frontend Developer',
                username: '@test',
            },
            {
                id: 3,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Frontend Developer',
                username: '@test',
            },
            {
                id: 4,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Frontend Developer',
                username: '@test',
            },
            {
                id: 5,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Frontend Developer',
                username: '@test',
            },
            {
                id: 6,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Frontend Developer',
                username: '@test',
            },
            {
                id: 7,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Frontend Developer',
                username: '@test',
            },
            {
                id: 8,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Frontend Developer',
                username: '@test',
            },
            {
                id: 9,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Frontend Developer',
                username: '@test',
            },
            {
                id: 10,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Frontend Developer',
                username: '@test',
            },
            {
                id: 11,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Frontend Developer',
                username: '@test',
            },
            {
                id: 12,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Frontend Developer',
                username: '@test',
            },
            {
                id: 13,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Frontend Developer',
                username: '@test',
            },
            {
                id: 14,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Frontend Developer',
                username: '@test',
            },
        ],
    },
    {
        id: 2,
        name: 'Backend Team',
        members: [
            {
                id: 15,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                is_owner: true,
                first_name: 'Алексей',
                role: 'Team Lead',
                username: '@test',
            },
            {
                id: 16,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Backend Developer',
                username: '@test',
            },
            {
                id: 17,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Backend Developer',
                username: '@test',
            },
            {
                id: 18,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Backend Developer',
                username: '@test',
            },
            {
                id: 19,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Backend Developer',
                username: '@test',
            },
            {
                id: 20,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Backend Developer',
                username: '@test',
            },
            {
                id: 21,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Backend Developer',
                username: '@test',
            },
            {
                id: 22,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Backend Developer',
                username: '@test',
            },
            {
                id: 23,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Backend Developer',
                username: '@test',
            },
            {
                id: 24,
                avatar: 'https://github.com/shadcn.png',
                last_name: 'Алексеев',
                first_name: 'Алексей',
                role: 'Backend Developer',
                username: '@test',
            },
        ],
    },
]
